name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.15
    with:
      linux_pre_build_command: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
      linux_build_command: 'swift build'
      linux_exclude_swift_versions: '[{"swift_version": "5.9"}, {"swift_version": "5.10"}, {"swift_version": "6.0"}]'
      enable_linux_static_sdk_build: true
      linux_static_sdk_pre_build_command: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
      linux_static_sdk_build_command: SWIFTTOOLSSUPPORTCORE_STATIC_LINK=1 swift build
      enable_windows_checks: false
      windows_pre_build_command: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
      windows_build_command: 'Invoke-Program swift build'
      enable_freebsd_checks: false
      freebsd_pre_build_command: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
      enable_android_sdk_build: true
      android_sdk_pre_build_command: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
      android_sdk_build_command: "swift build --build-tests --build-system native"
      enable_ios_checks: false
      enable_macos_checks: true
      macos_pre_build_command: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift.org"
      license_header_check_enabled: false
      unacceptable_language_check_enabled: false
      api_breakage_check_enabled: false
      format_check_enabled: false
